# -*- coding: utf-8 -*-
"""IDDFS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/164xgXfrVqdUJ4u6R8Z8BNJAMGcqOXnJ3
"""

WHITE=1
GREY=0
BLACK=-1

class GRAPH:

  def __init__(self,M):
    self.Matrix=M
    self.N=M.shape[0]
    self.parent= [None for i in range(self.N)]
    self.color= [WHITE for i in range(self.N)]

  def getParent(self,index):
        return self.parent[index]

  def getColor(self,index):
      return self.color[index]
  
  def setParent(self,index,P):
      self.parent[index] = P
      
  def setColor(self,index,color):
      self.color[index] = color
      
  def getAdjacent(self,index):
      A=[]
      for i,v in enumerate(self.Matrix[index,:]):
          if v!=0:
              A.append(i)
      return A

class IDDFS:

  def __init__(self,Graph,goal):
    self.G=Graph
    self.P=[]
    self.Goal=goal
  
  def Traversal(self,S,MaxD):
    for d in range(1,MaxD):
      self.G.parent= [None for i in range(self.G.N)]
      self.G.color= [WHITE for i in range(self.G.N)]
      self.P=[]
      if self.IDDFS_visit(S,d)==True:
        return True
    self.P.pop(0)
    return False
  
  def IDDFS_visit(self,node,d):
    
    self.P.append(node)
    self.G.setColor(node,BLACK)

    if node==self.Goal:
      return True
    elif len(self.P)==d:
      return False

    for v in self.G.getAdjacent(node):
      if self.G.getColor(v) == WHITE:
        if self.IDDFS_visit(v,d)==True:
          return True
        else:
          self.P.remove(v)
    return False

  def printPath(self):
    for u in self.P:
      print(u,end=' ')
    print(' ')
     
          
    

import numpy as np
M = np.array([[0,1,1,1,0,0,0,0],
              [1,0,0,0,1,1,0,0],
              [1,0,0,0,0,0,1,1],
              [1,0,0,0,0,0,0,1],
              [0,1,0,0,0,1,0,0],
              [0,1,0,0,1,0,1,0],
              [0,0,1,0,0,1,0,0],
              [0,0,1,1,0,0,0,0]])

Z= np.array([[0,1,1,0,0],
             [1,1,0,1,0],
             [1,0,0,1,1],
             [0,1,1,0,1],
             [0,0,1,1,0]])

#G = GRAPH(Z)
G = GRAPH(M)
search = IDDFS(G,5)
print(search.Traversal(0,4))
search.printPath()



WHITE=1
GREY=0
BLACK=-1

class GRAPH:

  def __init__(self,M):
    self.Matrix=M
    self.N=M.shape[0]
    self.parent= [None for i in range(self.N)]
    self.color= [WHITE for i in range(self.N)]

  def getParent(self,index):
        return self.parent[index]

  def getColor(self,index):
      return self.color[index]
  
  def setParent(self,index,P):
      self.parent[index] = P
      
  def setColor(self,index,color):
      self.color[index] = color
      
  def getAdjacent(self,index):
      A=[]
      for i,v in enumerate(self.Matrix[index,:]):
          if v!=0:
              A.append(i)
      return A

class DLS:

  def __init__(self,Graph,MaxD,goal):
    self.G=Graph
    self.P=[]
    self.D=MaxD
    self.level=1
    self.Goal=goal
  
  def Traversal(self,S):
    self.P.append(S)
    self.G.setColor(S,BLACK)

    if S==self.Goal:
      return True
    elif len(self.P)==self.D:
      return False

    for v in self.G.getAdjacent(S):
      if self.G.getColor(v) == WHITE:
        if self.Traversal(v)==True:
          return True
        else:
          self.P.remove(v)
    return False 

  def printPath(self):
    for u in self.P:
      print(u,end=' ')
    print(' ')
     
          
    

import numpy as np
M = np.array([[0,1,1,1,0,0,0,0],
              [1,0,0,0,1,1,0,0],
              [1,0,0,0,0,0,1,1],
              [1,0,0,0,0,0,0,1],
              [0,1,0,0,0,1,0,0],
              [0,1,0,0,1,0,1,0],
              [0,0,1,0,0,1,0,0],
              [0,0,1,1,0,0,0,0]])

Z= np.array([[0,1,1,0,0],
             [1,1,0,1,0],
             [1,0,0,1,1],
             [0,1,1,0,1],
             [0,0,1,1,0]])

#G = GRAPH(Z)
G = GRAPH(M)
search = DLS(G,3,5)
print(search.Traversal(0))
search.printPath()